### ISSUE TITLE
Device image credits?

### ISSUE THREAD

**Issue by ParkerK** [StartBootstrap/startbootstrap-new-age#25]
Is there somewhere that contains the links to the original device images this theme uses?

**Comment by rbar2** [comment]
@ParkerK, I'm a bit late to the party here, but this may be helpful for you or others: https://developer.apple.com/app-store/marketing/guidelines/ (downloadable image frames for Apple devices)

**Comment by davidtmiller** [comment]
https://github.com/pixelsign/html5-device-mockups is the repo we're using for the device mockups, so the licensing information should be there!
