### ISSUE TITLE
Possible to get iPhone X device-mockups?

### ISSUE THREAD

**Issue by houmie** [StartBootstrap/startbootstrap-new-age#39]
Thanks

**Comment by jgonfer** [comment]
I've added them on https://github.com/BlackrockDigital/startbootstrap-new-age/pull/45, once the PR is approved you'll be able to use them 😉

**Comment by davidtmiller** [comment]
We're now using a single screenshot from the device mockups library. If you want to use something different you can go here: https://github.com/pixelsign/html5-device-mockups
