### ISSUE TITLE
are these buttons (Device Mockups, Flexible Use) generated by files? I can't find the JPG file. Where is it generated?

### ISSUE THREAD

**Issue by ithjz** [StartBootstrap/startbootstrap-new-age#40]
Hello, are these buttons (Device Mockups, Flexible Use) generated by files?
I can't find the JPG file. Where is it generated?

![qq 20180425161917](https://user-images.githubusercontent.com/15103507/39234264-589cc112-48a5-11e8-82e8-6c8364a22a5b.jpg)
![qq 20180425160957](https://user-images.githubusercontent.com/15103507/39234270-5d6ee4c2-48a5-11e8-87a0-8b244b517291.jpg)

**Comment by woutervisee** [comment]
they're font awesome (FA) 4.7.0 icons. The CSS for FA is included in the html, then using that css the <i> tags get replaced with an icon.

**Comment by davidtmiller** [comment]
Those icons are Simple Line icons, which are now being brought in via CDN.
