### ISSUE TITLE
Can't Install via NPM

### ISSUE THREAD

**Issue by dhistira** [StartBootstrap/startbootstrap-new-age#53]
Trying to install via NPM but causing fail when installing in sub-directory

> C:\wamp64\www\randomofme.com>npm i startbootstrap-new-age
> npm WARN saveError ENOENT: no such file or directory, open 'C:\wamp64\www\package.json'
> npm WARN enoent ENOENT: no such file or directory, open 'C:\wamp64\www\package.json'
> npm WARN bootstrap@4.2.1 requires a peer of popper.js@^1.14.6 but none is installed. You must install peer dependencies yourself.
> npm WARN www No description
> npm WARN www No repository field.
> npm WARN www No README data
> npm WARN www No license field.
> 
> \+ startbootstrap-new-age@5.0.2
> added 6 packages from 13 contributors and audited 1940 packages in 66.221s
> found 0 vulnerabilities

Rest of node_modules installed on root (www), not on sub-directory, sub-directory still empty

> OS: Windows 10
> LocalServer: Apache on WAMP
> NPM Version: 6.5.0

**Comment by davidtmiller** [comment]
`npm install` is working with the most recent update. I recommend updating your version of npm and running a clean install.
