### ISSUE TITLE
Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by jrayga** [StartBootstrap/startbootstrap-new-age#57]
![image](https://user-images.githubusercontent.com/38303930/53710191-fb054380-3e76-11e9-9552-5f341c871fd5.png)

Good Day, I have this error on the `new-age.min.js`. I've used Angular and imported all the css and js on the angular.json. What causes this problem?

**Comment by toprakvo** [comment]
change navbarCollapse method in that javascript file as following:

// Collapse Navbar
  var navbarCollapse = function() {
    var mainNav = $('#mainNav');
    if (mainNav.length) {
      if ($("#mainNav").offset().top > 100) {
        $("#mainNav").addClass("navbar-shrink");
      } else {
        $("#mainNav").removeClass("navbar-shrink");
      }
    }

  };

**Comment by davidtmiller** [comment]
With the most recent change, this should be fixed up!
