### ISSUE TITLE
update device screenshots

### ISSUE THREAD

**Issue by avipars** [StartBootstrap/startbootstrap-new-age#60]
Firstly, I would like to thank you for making this great design available to us all for free. 

Secondly, Facebook offers a wide variety of device screenshots, they have the Galaxy S9, and some relatively new phones. Your project only has till the Galaxy S5. 

https://facebook.design/devices

It would be great if we can get updated devices once in a while!

THank you very much.

**Comment by davidtmiller** [comment]
We're now using a single screenshot from the device mockups library. If you want to use something different you can go here: https://github.com/pixelsign/html5-device-mockups
