### ISSUE TITLE
It doesn't compress the CSS

### ISSUE THREAD

**Issue by tegant-old** [StartBootstrap/startbootstrap-new-age#62]
Thanks for fixing the gulpfile to compress the js. It is now working:
```
gulp.watch(["./js/**/*", "!./js/**/*.min.js"], js);
```

However the css still doesn't compile.
I have custom css in new-age/css/
and ```gulp css``` ignores those.

This wasn't the case in the previous release.

Is there any chance you could fix this please?

**Comment by davidtmiller** [comment]
With the most recent update this should be fixed.
