### ISSUE TITLE
How can i change index file extension.

### ISSUE THREAD

**Issue by iqasim-com** [StartBootstrap/startbootstrap-new-age#65]
I am using old version of startbootstrao-new-page
Please let me know how can i add index.php instead of index.html.

Hi i am creating a website using php, using **startbootstrap-new-age** theme for quick development but i am little stuck.

I have make some changes in gulpfile to run index.php instead of index.html and it's working but when i did this scss function in gulpfile (which is responsible for converting SCSS into css) is not working as expected.

`
gulp.task('css:compile', function() {
  return gulp.src('./scss/**/*.scss')
    .pipe(sass.sync({
      outputStyle: 'expanded'
    }).on('error', sass.logError))
    .pipe(gulp.dest('./css'))
});`

It's not converting the variables but working fine for simple SCSS like :
**Working example**
`#mainNav {
  h1 {
    font-size: 20px;
    color: orange
  }
}`

**Not Working in this condition**
`#mainNav {
  h1 {
    font-size: 20px;
    color: **$orange-color**
  }
}`

**Comment by davidtmiller** [comment]
Gulp has been dropped as of the most recent update.
