### ISSUE TITLE
Which files are necessary for deploying?

### ISSUE THREAD

**Issue by AllenEllis** [StartBootstrap/startbootstrap-new-age#82]
Beautiful template, thanks. I've followed the directions under [Advanced Usage](https://github.com/StartBootstrap/startbootstrap-new-age#advanced-usage) and am ready to deploy the site, but the total size of my working directory is **381 MB**. 

<details>
  <summary>Breakdown per folder</summary>

  ```bash
  ncdu 1.14.2 ~ Use the arrow keys to navigate, press ? for help
--- /Users/allen/Sites/mysite-landing -----------------------------------------
  164.0 MiB [##########] /.git
  127.6 MiB [#######   ] /node_modules
   78.9 MiB [####      ] /device-mockups
    8.2 MiB [          ] /vendor
    2.2 MiB [          ] /img
  280.0 KiB [          ]  package-lock.json
   48.0 KiB [          ] /scss
   16.0 KiB [          ] /css
   12.0 KiB [          ]  index.html
   12.0 KiB [          ]  .DS_Store
    8.0 KiB [          ] /js
    4.0 KiB [          ]  README.md
    4.0 KiB [          ]  gulpfile.js
    4.0 KiB [          ]  package.json
    4.0 KiB [          ]  LICENSE
    4.0 KiB [          ]  heroku-build.js
    4.0 KiB [          ]  .browserslistrc
    4.0 KiB [          ]  .travis.yml
    4.0 KiB [          ]  .gitignore
  ```
</details>

Is there a build script I can/should run that would essentially copy just the required files to a production server? In my case, I want to drop this page into an existing Django app. I'm a bit new to npm & gulp.

Thanks!

**Comment by AllenEllis** [comment]
In case it's helpful to anyone else, I modified `gulpfile.js` and added the following:

```javascript

function dist() {
  return gulp
  .src([
    'index.html',
    './**/js/*',
    './**/css/*',
    './**/img/*',
    './**/vendor/*/*/*',
    './**/device-mockups/*.css',
    './**/device-mockups/iphone_12',
  ])
  .pipe(gulp.dest('./dist'));
}
```

Then on the terminal I ran `gulp dist`, and it saved all the necessary files into `/dist`.

**Comment by davidtmiller** [comment]
The dev environment has been changed, so the new build would be everything that compiles into `dist`
